### ISSUE TITLE
Is there anyway to customize plotting to use tick data?

### ISSUE THREAD

**Issue by huuquynh** [happydasch/btplotting#10]
Hello,

This is not an issue at all, and maybe I should ask Backtrader's owner, but I think Daniel is not focus on plotting, he built the system. And you are a special one on plotting when fork to bokeh and make it more beautiful and useful when backtest or live trade.

The idea is when we got the tick data, could plotting it as footprint bar chart? If you don't have time, please talk to me the right way to implement this.

Thank you very much!

**Comment by happydasch** [comment]
you can plot tick data, maybe i just don't understand correctly, what you describe there.

**Comment by huuquynh** [comment]
Something likes this:

![footprint-chart](https://user-images.githubusercontent.com/145587/105113527-b54bd580-5af7-11eb-8fb9-d137f3875fd0.png)

**Comment by happydasch** [comment]
i understand now. i won't have the possibility to implement this. also since the generation of plots is very close to the way backtrader is generating its plots this may be very hard to implement with btplotting. there may be other issues related to data processing, some of the data processing code is not working correctly.

**Comment by huuquynh** [comment]
Thank you for your answer! I will close this issue.

But as a bokeh guru, do you think it could be implement independent in bokeh/plotly, no relative to backtrader?

Thank you very much for your time!

**Comment by happydasch** [comment]
sure, that would be no problem.

**Comment by huuquynh** [comment]
Could you please to show me the guide/short direction to do with bokeh/plotly? Could it run with realtime data tick? I will do a research and learn to implement it.

Thank you!

**Comment by huuquynh** [comment]
I've checked around with plotly, and I can imagine the way to implement.

Thanks for your guide and your time. Best wishes!

**Comment by The1iAmNeo** [comment]
> I've checked around with plotly, and I can imagine the way to implement.
> 
> Thanks for your guide and your time. Best wishes!

@huuquynh were you ever able to figure this out ... i want to do footprint bars as well

**Comment by httran13** [comment]
> > I've checked around with plotly, and I can imagine the way to implement.
> > Thanks for your guide and your time. Best wishes!
> 
> @huuquynh were you ever able to figure this out ... i want to do footprint bars as well

@huuquynh  same did you figure it out? or @The1iAmNeo

**Comment by httran13** [comment]
https://stackoverflow.com/a/69333395/5642133

@huuquynh @The1iAmNeo  I found this

**Comment by The1iAmNeo** [comment]
@httran13 did it actually work for you?
