### ISSUE TITLE
Getting an error trying to plot the PSAR indicator

### ISSUE THREAD

**Issue by Jake0303** [happydasch/btplotting#15]
Trying to plot the built-in indicator from backtrader PSAR and getting an error.

`self.psar[i] = bt.ind.PSAR(self.datas[i],period=2,af=0.02,afmax=0.2)  # parabolic sar`

Error :  `Exception: Sorry, unsupported marker: ".". Please report to GitHub.``

StackTrace : 

> File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\app.py", line 567, in plot
>     filter=filter)
>   File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\app.py", line 318, in create_figurepage
>     self._blueprint_strategy(figid, filter)
>   File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\app.py", line 209, in _blueprint_strategy
>     figure.plot(c)
>   File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\figure.py", line 671, in plot
>     self.plot_indicator(obj)
>   File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\figure.py", line 855, in plot_indicator
>     self._plot_indicator_observer(obj)
>   File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\figure.py", line 477, in _plot_indicator_observer
>     + f' "{marker}". Please report to GitHub.')
> Exception: Sorry, unsupported marker: ".". Please report to GitHub.

**Comment by Jake0303** [comment]
@happydasch if you're available I would greatly appreciate it.

**Comment by happydasch** [comment]
He  Jacob, so for the unsupported  marker, this should not show up. but  anyway, the psar will not render correctly. this will either work when using a different plot lib like plotly or by fixing  the data proceessing. both solutions will  not  happen that fast.

**Comment by happydasch** [comment]
i wanted to add a fix for your issue but  i could not  even reproduce your issue. did you use the latest github code or the versioned zip? try out the github code if the issue exists without your fix.

**Comment by Jake0303** [comment]
> i wanted to add a fix for your issue but i could not even reproduce your issue. did you use the latest github code or the versioned zip? try out the github code if the issue exists without your fix.

I'm on version 0.1.1 and still get the issue, I tried pip install git+https://github.com/happydasch/btplotting --upgrade

**Comment by Jake0303** [comment]
> i wanted to add a fix for your issue but i could not even reproduce your issue. did you use the latest github code or the versioned zip? try out the github code if the issue exists without your fix.

My fault, I had an old version of backtrader-plotting which bt-plotting is built on top of. I upgraded to 2.0 and works like a charm. We good.
