### ISSUE TITLE
How to plot bar changing with tick changes?

### ISSUE THREAD

**Issue by shaoy06** [happydasch/btplotting#17]
Hi,
My trade strategy used 30min BNB data to send signal, and with Tick level data for trailing. 
With your great btplotting tool, I am able to do live trading plotting ( together with bt-ccxt-store), but my issue is the 30min bar is not changing according to the receiving of tick data. It receives the 30min bar data for once, and then no changes... ( please see attached pic) 
![image](https://user-images.githubusercontent.com/87840832/130587033-3200ed77-2913-4551-a166-758c67eadbf5.png)

here is the data I use:

    hist_start_date = datetime.datetime.utcnow() - datetime.timedelta(hours=249)
    data = store.getdata(
        dataname='BNB/USDT',
        name="BNB/USDT",
        dtformat=('%Y-%m-%d %H:%M:%S.%f'), 
        timeframe=bt.TimeFrame.Ticks,
        fromdate=hist_start_date,
        #ohlcv_limit=99999,
        nullvalue=0.0
    )
    tframes = dict(
        ticks=bt.TimeFrame.Ticks,
        microseconds=bt.TimeFrame.MicroSeconds,
        seconds=bt.TimeFrame.Seconds,
        minutes=bt.TimeFrame.Minutes,
        days=bt.TimeFrame.Days,
        weekly=bt.TimeFrame.Weeks,
        monthly=bt.TimeFrame.Months
    )

    cerebro.resampledata(
        data,
        timeframe=tframes['minutes'],
        compression=30
    ) #把行情数据对象注入引擎

So my question is can btplotting modifying the 30min bar as long as it receives tick data? Many thanks!

**Comment by happydasch** [comment]
you resample data, so data will forward once the period is over. try using replay.

**Comment by shaoy06** [comment]
> you resample data, so data will forward once the period is over. try using replay.

Hi, I use"replay" and tried again. Seems the result is same.. 
![image](https://user-images.githubusercontent.com/87840832/130622855-e13960d9-1057-41dc-8cf4-de6bc2d47e75.png)

**Comment by shaoy06** [comment]
> you resample data, so data will forward once the period is over. try using replay.

Hi, I used "replay" to try, but seems the result is same... 
![image](https://user-images.githubusercontent.com/87840832/130622969-6674cd63-57c3-4470-ba4c-069472b42433.png)

**Comment by happydasch** [comment]
should work now with latest commit

**Comment by shaoy06** [comment]
should work now with latest commit

Thanks happydasch. 
Just want to add one point if others want to know: "drop_newest = True" is a must if you want to show changes on larger timeframe bars.  
`        hist_start_date = dt.datetime.utcnow() - dt.timedelta(minutes=500)
        data = store.getdata(
            dataname='%s/%s' % (COIN_TARGET, COIN_REFER),
            name='%s%s' % (COIN_TARGET, COIN_REFER),
            timeframe=bt.TimeFrame.Minutes,
            fromdate=hist_start_date,
            compression=1,
            ohlcv_limit=99999,
            drop_newest = True
        )

        # Add the feed
        cerebro.adddata(data)
        cerebro.replaydata(data,timeframe=bt.TimeFrame.Minutes,compression=30,name='30_min')`

**Comment by shaoy06** [comment]
Thanks happydasch.
Just want to add one point if others want to know: "drop_newest = True" is a must if you want to show changes on larger timeframe bars.

`        hist_start_date = dt.datetime.utcnow() - dt.timedelta(minutes=500)
        data = store.getdata(
            dataname='%s/%s' % (COIN_TARGET, COIN_REFER),
            name='%s%s' % (COIN_TARGET, COIN_REFER),
            timeframe=bt.TimeFrame.Minutes,
            fromdate=hist_start_date,
            compression=1,
            ohlcv_limit=99999,
            drop_newest = True
        )

        # Add the feed
        cerebro.adddata(data)
        cerebro.replaydata(data,timeframe=bt.TimeFrame.Minutes,compression=30,name='30_min')`
