### ISSUE TITLE
Got this warning:DataFrame is highly fragmented

### ISSUE THREAD

**Issue by 630362055** [happydasch/btplotting#19]
I have 86 symbols which symbol has 8640 rows of kline data(using bt.feeds.PandasData)
When i run backtest, I got this warning:
`C:\Users\63036\Anaconda3\lib\site-packages\btplotting\app.py:514: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df[source_id] = new_line
C:\Users\63036\Anaconda3\lib\site-packages\btplotting\app.py:524: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df['index'] = indices
C:\Users\63036\Anaconda3\lib\site-packages\btplotting\app.py:525: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead.  To get a de-fragmented frame, use `newframe = frame.copy()`
  df['datetime'] = clkidx
`
![image](https://user-images.githubusercontent.com/25970108/132103289-c590cac2-ebee-4acc-bfa0-4a1ebf71779d.png)

**Comment by happydasch** [comment]
thanks to @GF-Huang for fixing this issue
