### ISSUE TITLE
webapp limit to "localhost" visiting is not reasonable, is it possible to add an args for customization ?

### ISSUE THREAD

**Issue by dindom999** [happydasch/btplotting#20]
So that the server can run the webapp, and the other pc on the same lan can visit it.

**Comment by happydasch** [comment]
you can set the ENV var BOKEH_ALLOW_WS_ORIGIN to *:

`BOKEH_ALLOW_WS_ORIGIN=* python ...`

**Comment by dindom999** [comment]
I think we should add an argv "address=0.0.0.0" here, or it won't work even set ENV BOKEH_ALLOW_WS_ORIGIN=*
https://github.com/happydasch/btplotting/blob/e266eb4a02f4785bc31068dc41cb4ec30c5b67f1/btplotting/webapp.py#L55

**Comment by happydasch** [comment]
Sny patches / pull requests are welcome
