### ISSUE TITLE
Exception: Sorry, unsupported marker: "8". Please report to GitHub.`

### ISSUE THREAD

**Issue by Jake0303** [happydasch/btplotting#22]
Backtest successfully completes but won't plot.
**How to reproduce**
1. Using ibstore
2. Have multi data (2 is enough)
3. Have strategy that uses the psar indicator
4. Backtest or run live

Full stacktrace:
`Traceback (most recent call last):
  File "C:\Users\Jacob\Desktop\Epicrise\cerebroHelper.py", line 262, in cerebro_helper_backtest
    self.cerebro.plot(p)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\backtrader\cerebro.py", line 991, in plot
    start=start, end=end, use=use)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\app.py", line 567, in plot
    filter=filter)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\app.py", line 318, in create_figurepage
    self._blueprint_strategy(figid, filter)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\app.py", line 207, in _blueprint_strategy
    figure.plot(parent)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\figure.py", line 649, in plot
    self.plot_observer(obj)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\figure.py", line 828, in plot_observer
    self._plot_indicator_observer(obj)
  File "C:\Users\Jacob\AppData\Roaming\Python\Python37\site-packages\btplotting\figure.py", line 456, in _plot_indicator_observer
    + f' "{marker}". Please report to GitHub.')
Exception: Sorry, unsupported marker: "8". Please report to GitHub.`

**Comment by happydasch** [comment]
The latest code in repository should work fine

**Comment by Jake0303** [comment]
> The latest code in repository should work fine

@happydasch I still get the error, I think it's actually when you use more than 8 symbols.

I'm trying NVDA,HOLX,PKI,CTLT,TMO,FTNT,PANW,DT,KEYS,TGH,IBP,METC,UPST,RM,SC

**Comment by happydasch** [comment]
you seem not to be using the latest code. i tried some simple code, works well.

```
from btplotting import BacktraderPlotting

import backtrader as bt


class St(bt.Strategy):

    def __init__(self):
        self.psar = bt.indicators.ParabolicSAR()


data1 = bt.feeds.GenericCSVData(
    dataname='data/YAHOO_AJRD_Days_1_2018-01-01_None_None.csv',
    dtformat='%Y-%m-%d', openinterest=-1)
data2 = bt.feeds.GenericCSVData(
    dataname='data/YAHOO_CXM_Days_1_2018-01-01_None_None.csv',
    dtformat='%Y-%m-%d', openinterest=-1)

cerebro = bt.Cerebro()
cerebro.addstrategy(St)
cerebro.adddata(data1)
cerebro.adddata(data2)
cerebro.run()

p = BacktraderPlotting(style='bar')
cerebro.plot(p)

```

**Comment by Jake0303** [comment]
> you seem not to be using the latest code. i tried some simple code, works well.
> 
> ```
> from btplotting import BacktraderPlotting
> 
> import backtrader as bt
> 
> 
> class St(bt.Strategy):
> 
>     def __init__(self):
>         self.psar = bt.indicators.ParabolicSAR()
> 
> 
> data1 = bt.feeds.GenericCSVData(
>     dataname='data/YAHOO_AJRD_Days_1_2018-01-01_None_None.csv',
>     dtformat='%Y-%m-%d', openinterest=-1)
> data2 = bt.feeds.GenericCSVData(
>     dataname='data/YAHOO_CXM_Days_1_2018-01-01_None_None.csv',
>     dtformat='%Y-%m-%d', openinterest=-1)
> 
> cerebro = bt.Cerebro()
> cerebro.addstrategy(St)
> cerebro.adddata(data1)
> cerebro.adddata(data2)
> cerebro.run()
> 
> p = BacktraderPlotting(style='bar')
> cerebro.plot(p)
> ```

I'm very confident I have the latest code, try 9 symbols. I think it's something to do with the Data Trades Observer

![image](https://user-images.githubusercontent.com/5394743/133664230-720cd639-9c83-4637-bd30-82854d6b80e2.png)

**Comment by happydasch** [comment]
Please provide some code to reproduce the issue you experience.

**Comment by happydasch** [comment]
> 
> I'm very confident I have the latest code, try 9 symbols.

I am very confident, you don't use the latest code available. Based on the error message, based on the plot screenshot. Its some outdate code you are using.

**Comment by Jake0303** [comment]
`from btplotting import BacktraderPlotting

import backtrader as bt


class St(bt.Strategy):

    def __init__(self):
        self.psar = bt.indicators.ParabolicSAR()


ibstore = bt.stores.IBStore(host='127.0.0.1', port=7496, reconnect=-1)  
data = None
stockkwargs = dict()

stockkwargs = dict(timeframe=bt.TimeFrame.Days,
                   compression=1,
                   historical=True,
                   fromdate=datetime.datetime.now()-datetime.timedelta(days=30),
                   todate=datetime.datetime.now(),
                   tz=pytz.timezone('US/Eastern'))
cerebro = bt.Cerebro()
exchangeType = '-STK-SMART-'
symbols = 'MSFT,AAPL,FB,NFLX,SPY,QQQ,GE,F,GS,VZ,NVDA'
for s in symbol.split(','):
  data = ibstore.getdata(dataname=str(s) + exchangeType + currency, **stockkwargs)
  cerebro.adddata(data1)

cerebro.addstrategy(St)
cerebro.run()

p = BacktraderPlotting(style='bar')
cerebro.plot(p)
`
If you have Discord let me know : https://discord.gg/mwPVXnUJ

**Comment by happydasch** [comment]
so if the error still happens with latest code then give me a note. i assume its due to the old code. cannot really guess what may else happen. the error should happen at line 447 which would match latest code.

https://github.com/happydasch/btplotting/blob/78b062b9139c686b5edb713575c52989a7f234b2/btplotting/figure.py#L447

**Comment by Jake0303** [comment]
> so if the error still happens with latest code then give me a note. i assume its due to the old code. cannot really guess what may else happen. the error should happen at line 447 which would match latest code.
> 
> https://github.com/happydasch/btplotting/blob/78b062b9139c686b5edb713575c52989a7f234b2/btplotting/figure.py#L447

I have the latest code, recently you added the address argument in plot.py

```python
class LivePlotAnalyzer(bt.Analyzer):

    params = (
        ('scheme', Blackly()),
        ('style', 'bar'),
        ('lookback', 23),
        ('address', 'localhost'),
        ('port', 80),
        ('title', None),
    )
```

**Comment by Jake0303** [comment]
> so if the error still happens with latest code then give me a note. i assume its due to the old code. cannot really guess what may else happen. the error should happen at line 447 which would match latest code.
> 
> https://github.com/happydasch/btplotting/blob/78b062b9139c686b5edb713575c52989a7f234b2/btplotting/figure.py#L447

@happydasch it was the datatrades

I commented out cerebro.py line 1248

```python
#else:
#strat._addobserver(False, observers.DataTrades)
```

**Comment by happydasch** [comment]
It seems, the error gets triggered after adding the at least 8 files. should be fixed by changing the markers to something, bokeh supoorts.
