### ISSUE TITLE
Turn off debug messages from Bokeh

### ISSUE THREAD

**Issue by lawrni** [happydasch/btplotting#28]
Firstly - what an absolutely great library!  Does exactly what I was looking for and more.

One slight niggle is that I seem to see all the Bokeh Debug messages at the command line output.  Any easy way to turn these off would be great.  I had a go myself but failed.

**Comment by huuquynh** [comment]
The simple way to hide debug/warning message in application:

```
import warnings
warnings.filterwarnings("ignore")
```
