### ISSUE TITLE
Solution for someone if encounters "TypeError: <class '__main__.XxxClass'> is a built-in class" in Jupyter

### ISSUE THREAD

**Issue by GF-Huang** [happydasch/btplotting#30]
In Jupyter you may try to plot to single browser tab with `iplot=False`:
```py
plot = btplotting.BacktraderPlotting()
cerebro.plot(plot, iplot=False)
```
You may encounters `TypeError: <class '__main__.YourStrategyClass'> is a built-in class` error.

Then try this:
```py
plot = btplotting.BacktraderPlotting()
plot.tabs.remove(btplotting.tabs.SourceTab)
cerebro.plot(plot, iplot=False)
```

**Comment by happydasch** [comment]
I have added a catch exceptions for source code viewing, will add the details for running in jupyter in readme
