### ISSUE TITLE
Plotting empty page.

### ISSUE THREAD

**Issue by GF-Huang** [happydasch/btplotting#33]
![image](https://user-images.githubusercontent.com/4510984/170671734-ee51abe8-424a-40fb-b15e-1db73dfe4ae2.png)

**Comment by GF-Huang** [comment]
After disable `CORS`, issue disappeared.

![image](https://user-images.githubusercontent.com/4510984/170696395-a25488b2-986a-49ab-b0d3-4496d1855208.png)

**Comment by huuquynh** [comment]
I think my error same as you: https://github.com/happydasch/btplotting/issues/35

Could you please to tell how to fix CORS to solve this issue? Thanks!

**Comment by GF-Huang** [comment]
After some time it has automatically returned to normal.

**Comment by happydasch** [comment]
i am not really sure if this is still a issue. open a new one if with latest code the issue is still there.
