### ISSUE TITLE
`BacktraderPlottingOptBrowser` seems not work in VSCode Jupyter

### ISSUE THREAD

**Issue by GF-Huang** [happydasch/btplotting#36]
![image](https://user-images.githubusercontent.com/4510984/177175398-4c162bfd-5f77-4afb-833e-82b9583ae91f.png)

![image](https://user-images.githubusercontent.com/4510984/177175361-7d8c8d90-6762-4457-b91b-01adfc062fc6.png)

**Comment by happydasch** [comment]
added a fix for this
