### ISSUE TITLE
ImportError: cannot import name 'Panel' from 'bokeh.models.widgets'

### ISSUE THREAD

**Issue by neversleep007** [happydasch/btplotting#42]
<img width="1594" alt="image" src="https://user-images.githubusercontent.com/34454079/208830316-56a0bf46-5c1b-4585-afd5-e54b0372b282.png">

when I run btplotting on the mac, I am having this issue. shall i uninstall backtrader_plotting first? when i tried to uninstall backtrader_plotting , it was not founded. please advise me on how to fix this issue.

**Comment by happydasch** [comment]
try a lower bokeh version.

**Comment by YingJie-Zhao** [comment]
I met the same problem with @neversleep007 and I have tried some different versions of bokeh.
However I still can't solve this problem, could you please tell me the version of bokeh used by bt_plotting currently?
@happydasch

**Comment by YingJie-Zhao** [comment]
@neversleep007
Check [this](https://discourse.bokeh.org/t/changed-api-bokeh-models-widgets-tabs-and-panel-gone/9710) out.
I tried the way mentioned in bokeh community and it seems worked for me.

**Comment by happydasch** [comment]
> I met the same problem with @neversleep007 and I have tried some different versions of bokeh.
> 
> However I still can't solve this problem, could you please tell me the version of bokeh used by bt_plotting currently?
> 
> @happydasch 

The latest supported version of bokeh is 2.4.3

3.0 and above is not supported, since it has some major changes.

**Comment by happydasch** [comment]
added support for bokeh 3.1, closing
