### ISSUE TITLE
The last candle is missing

### ISSUE THREAD

**Issue by helloboy110** [happydasch/btplotting#48]
The last candle is missing

**Comment by happydasch** [comment]
can you provide more details?

**Comment by helloboy110** [comment]
run demos/blackly_single.py
![image](https://github.com/happydasch/btplotting/assets/13136062/273f18dc-a9d5-4afd-9ad8-1cddd0414c0a)
![image](https://github.com/happydasch/btplotting/assets/13136062/f0d0d792-a065-469a-b392-826759155e1c)
bokeh plot:
![image](https://github.com/happydasch/btplotting/assets/13136062/e69ab68a-42b3-4081-b5f0-e4eab9070d4a)

**Comment by happydasch** [comment]
The last candle is not complete so it will not be generated. Will look into changing this behaviour.

**Comment by zgpnuaa** [comment]
It does not draw the first candlestick whether it is in live trading or backtesting. Instead, it starts drawing from the second candlestick. The overall time remains unchanged, meaning that the chart starts from the second candlestick but with time starting from the first candlestick's time. This results in all candlesticks having incorrect timestamps, as there is a shift of one period in time. For example, when plotting 30-minute candlesticks, the OHLC data displayed at 10:00 actually corresponds to 10:30 OHLC data and so on.

> 2023/06/19 10:00:00, 1_prenext: open:271.758-high:271.758-low:271.168-close:271.258 
   2023/06/19 10:30:00, 2_prenext: open:271.228-high:271.768-low:268.408-close:268.878
   2023/06/19 11:00:00, 3_prenext: open:268.898-high:270.458-low:268.898-close:269.238 
   2023/06/19 11:30:00, 4_prenext: open:269.238-high:269.238-low:266.868-close:268.158 
![image](https://github.com/happydasch/btplotting/assets/38033949/3f961dad-97d2-44a8-ad83-d9bbda391969)
![image](https://github.com/happydasch/btplotting/assets/38033949/943f5372-0418-482c-9684-0a86f6639115)

**Comment by qsyao** [comment]
same question, expecting a nice fix ! @happydasch

**Comment by Balzac1799** [comment]
It seems that change [this line](https://github.com/happydasch/btplotting/blob/b3d72f212cc6b4fbdcbe3d30bcf2ff4125890c3d/btplotting/clock.py#L163) to `if c_start and c_start >= t_end` can fix the missing first candle error
