### ISSUE TITLE
Graphs oversized

### ISSUE THREAD

**Issue by Onepamopa** [happydasch/btplotting#5]
I'm running a backtest with a period of 10 years and the graphs are just enormous.
How to resize/scale them properly ?

**Comment by happydasch** [comment]
could you provide a screenshot of what is oversized?

Also if there is too much data, in backtrader you can create multiple figures with the param numfigs=n but this is not supported in btplotting.  

when the tabs are oversized, this is not that easily fixable, but you could remove the sourcecode tab, which will stretch all tabs if there is a long line in your code. 

You can also adjust aspectratio values for indicators, plots, observers individually.

**Comment by Onepamopa** [comment]
The tabs are not oversized, the graphs are. I'm @ 1600x900 res and the graphs are 30% off the screen. I'll try to provide screens tomorrow.

**Comment by happydasch** [comment]
take a look at this params then:

       ```
 # Aspect ratios for different figure types
        self.data_aspectratio = 2.5
        self.vol_aspectratio = 5.0
        self.obs_aspectratio = 5.0
        self.ind_aspectratio = 5.0
```
jusst provide them when creating BacktraderPlotting object.

```
    p = BacktraderPlotting(data_aspectratio=2.5, vol_aspectratio = 5.0, obs_aspectratio = 5.0, ind_aspectratio = 5.0)
    cerebro.plot(p)
```

the higher the value, the smaller the height.

**Comment by happydasch** [comment]
i use internally the following values which will look mostly like backtrader plotting:
`
                data_aspectratio=2.5,
                vol_aspectratio=5.5,
                obs_aspectratio=8.5,
                ind_aspectratio=11.5,`

**Comment by happydasch** [comment]
the reason for this is, that backtrader_plotting was just using one value for aspect ratios. i kept it close to to code of backtrader_plotting, since i hope, all the fixes i added will be added to upstream.

**Comment by happydasch** [comment]
for the aspectratio calculation, you can use the following formula:

height=1000/aspectratio

**Comment by happydasch** [comment]
it will adapt to the width of the browser window, so if your resolution is 1600, with a aspect ratio of 10 the height will be 160 px

**Comment by happydasch** [comment]
i assume, the aspectratio settings did work? Please reopen if not.
