### ISSUE TITLE
Problem with toolbox, the toolbar is not displayed on the chart

### ISSUE THREAD

**Issue by cryptorevizor** [happydasch/btplotting#6]
Hi,
in my strategy code I had a long line of code, something like this:
`if self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and self.position.size > 0 and`
and due this tabs "source code" just crashes all html file
![Screenshot_2](https://user-images.githubusercontent.com/45230803/93210621-995eae80-f768-11ea-8fa6-5c1168be7232.png)

after i styled my strategy code i got the correct display of the toolbar.  BINGO :)

**Comment by happydasch** [comment]
Yes, this is known behavior. If a line is too long it will make the pre field longer and this will make all tabs longer.

I will most probably replace the pre field with a div and convert the source code to html. This will allow better control of the width, I think.

**Comment by happydasch** [comment]
would love to hear back, if you have any more issues

**Comment by helgridly** [comment]
I'm not sure if this is the same issue, but I'm not seeing the toolbox either. So no pan/zoom controls for me. I'm running in a Jupyter notebook if that makes any difference. Also, the cell output contains the graph followed by a huge amount (like 20x the graph height) of blank whitespace.

**Comment by GF-Huang** [comment]
> I'm not sure if this is the same issue, but I'm not seeing the toolbox either. So no pan/zoom controls for me. I'm running in a Jupyter notebook if that makes any difference. Also, the cell output contains the graph followed by a huge amount (like 20x the graph height) of blank whitespace.

Same issue. I use btplotting in JupyterLab, it does not show the toolbox at right side.

![image](https://user-images.githubusercontent.com/4510984/157507691-482c43e4-c463-432d-b2d4-13c2aa6248a1.png)
