### ISSUE TITLE
_skipnan bug

### ISSUE THREAD

**Issue by ltaljaard** [happydasch/btplotting#64]
When you specify _skipnan in your lineinfo it does not skip the nan's i.e. it continues to plot the line. It seems it is due to the code at th end of clock.py get_data() where interpolate() is called for the lines in the "skipnan" list. this might be a problem only when you also have fill speficied for your skipnan lines.

I think it should do the opposite for _skipnan lines and NOT interpolate anything. I have changed the code like this and it now skips the nan's (even for lines where fills are also specified):

Current code in get_data():
`if name in skipnan:`
`    df[name] = df[name].interpolate()`
`elif name not in fillnan:`
`    df[name] = df[name].fillna(method='ffill')`

Modified code that works for me:
`if name in skipnan:`
`    pass`
`elif name not in fillnan:`
`    df[name] = df[name].fillna(method='ffill')`

PS: if gong to this this then could just as well call ffill() here instead of the deprecated fillna(). It would then get rid of the current "FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.  df[name] = df[name].fillna(method='ffill')" runtime warning as well:

`if name in skipnan:`
`    pass`
`elif name not in fillnan:`
`    df[name] = df[name].ffill()`

**Comment by happydasch** [comment]
Took a bit, but thanks a lot for the bug fix.

**Comment by ltaljaard** [comment]
Could you publish a new release v 0.2.2 that includes this fix?

**Comment by happydasch** [comment]
yes, added a new release
