### ISSUE TITLE
Y-axis auto scaling

### ISSUE THREAD

**Issue by tlchan5** [happydasch/btplotting#9]
Hello. Firstly, thanks for bringing such an amazing library to plot the graph!

I am currently using it to plot the live data.
However, the bar size looks very small in the graph. I think it's because the y-axis starts at 0. 
I wonder is there any param I can set such that the y-axis can be auto-scaled? 

![image](https://user-images.githubusercontent.com/25591449/102625342-4e49a280-4180-11eb-95b9-1ded8c7383b9.png)

Thank you in advance.

**Comment by happydasch** [comment]
You seem to be plotting some signals at 0 so it scales over everything that is being plotted there

**Comment by tlchan5** [comment]
You're right! Thanks for spotting the issue. Will close this issue.

**Comment by saukendar-sklor** [comment]
First, great work, love this package.


I'm having what I think is a similar problem.
Running the blackly_single demo in jupyter, The volume scale is crushing the price scale to a straight line.
How can I make the 2 axes scale independently?

![VirtualBoxVM_2021-02-25_23-22-39](https://user-images.githubusercontent.com/79681642/109254658-7842c500-77c0-11eb-9f08-a81ca98bb353.png)

Thanks, very much.
